//
//  ScrollViewMenuItem.swift
//  UIKit-Swift
//
//  Created by Kamil Gomółka on 13/04/2022.
//

import UIKit

enum ScrollViewMenuItem: String, MenuItemProtocol {
    case vertical
    case horizontal
    case twoDirections
    
    var name: String {
        return rawValue.autoGeneratedMenuItemName
    }
    
	var viewController: UIViewController? {
		switch self {
		case .vertical:
			return ScrollViewVerticalViewController()
		case .horizontal:
			return ScrollViewHorizontalViewController()
		case .twoDirections:
			return ScrollViewTwoDirectionsViewController()
		}
	}
}
