//
//  ScrollViewMenuItem.swift
//  UIKit-Storyboard
//
//  Created by Kamil Gomółka on 06/12/2021.
//

import UIKit

enum ScrollViewMenuItem: String, MenuItemProtocol {
    case vertical
    case horizontal
    case twoDirections
    
    var name: String {
        return rawValue.autoGeneratedMenuItemName
    }
    
	var viewController: UIViewController? {
		switch self {
		case .vertical:
			return ScrollViewVerticalViewController()
		case .horizontal:
			return ScrollViewHorizontalViewController()
		case .twoDirections:
			return ScrollViewTwoDirectionsViewController()
		}
	}
}
