//
//  TableViewMenuItem.swift
//  UIKit-Swift
//
//  Created by Kamil Gomółka on 13/04/2022.
//

import UIKit

enum TableViewSelectionMenuItem: String, MenuItemProtocol {
    case single
    case singleWithDeselect
    case multiple
    
    var name: String {
        return rawValue.autoGeneratedMenuItemName
    }
    
	var viewController: UIViewController? {
        switch self {
        case .single:
            return TableViewSelectionSingleViewController()
        case .singleWithDeselect:
            return TableViewSelectionWithDeselectViewController()
        case .multiple:
            return TableViewSelectionMultipleViewController()
        }
    }
}
