//
//  MainMenuItem.swift
//  UIKit-Swift
//
//  Created by Kamil Gomółka on 15/03/2022.
//

import UIKit

enum MainMenuItem: String, MenuItemProtocol {
    case allControls
    case label
    case button
	case textField
    
    var name: String {
		switch self {
		case .allControls:
			return rawValue.autoGeneratedMenuItemName
		case .label:
			return rawValue.autoGeneratedMenuItemName
		case .button:
			return rawValue.autoGeneratedMenuItemName
		case .textField:
			return "TextField"
		}
    }
    
    var viewController: UIViewController? {
        switch self {
        case .allControls:
            return AllControlsViewController()
        case .label:
            return LabelMenuViewController()
        case .button:
            return ButtonMenuViewController()
		case .textField:
			return TextFieldMenuViewController()
        }
    }
}
