//
//  MainMenuItem.swift
//  UIKit-Swift
//
//  Created by Kamil Gomółka on 15/03/2022.
//

import UIKit

enum MainMenuItem: String, MenuItemProtocol {
    case allControls
    case label
    
    var name: String {
        return rawValue.autoGeneratedMenuItemName
    }
    
    var viewController: UIViewController? {
        switch self {
        case .allControls:
            return AllControlsViewController()
        case .label:
            return LabelMenuViewController()
        }
    }
}
