//
//  TableViewEditingMenuItem.swift
//  UIKit-Swift
//
//  Created by Kamil Gomółka on 15/04/2022.
//

import UIKit

enum TableViewEditingMenuItem: String, MenuItemProtocol {
	case addAndDelete
	case reorder
	case swipeActions
	
	var name: String {
		return rawValue.autoGeneratedMenuItemName
	}
	
	var viewController: UIViewController? {
		switch self {
		case .addAndDelete:
			return TableViewAddAndDeleteViewController()
		case .reorder:
			return TableViewReorderViewController()
		case .swipeActions:
			return TableViewSwipeActionsViewController()
		}
	}
}
