//
//  MenuItemProtocol.swift
//  UIKit-Swift
//
//  Created by Kamil Gomółka on 15/03/2022.
//

import Foundation
import UIKit

protocol MenuItemProtocol: CaseIterable {
    var name: String { get }
    var viewController: UIViewController? { get }
}

extension MenuItemProtocol {
    func instantiateViewController() -> UIViewController? {
        let viewController = viewController
        
        viewController?.title = name
        
        return viewController
    }
}

extension String {
    var autoGeneratedMenuItemName: String {
        var result = ""
        
        for character in self {
            if result.isEmpty {
                result.append(character.uppercased())
            } else if character.isUppercase {
                result.append(" " + character.lowercased())
            } else {
                result.append(character)
            }
        }
        
        return result
    }
}
