//
//  TableViewSeparatorStyleMenuItem.swift
//  UIKit-Swift
//
//  Created by Kamil Gomółka on 13/04/2022.
//

import UIKit

enum TableViewSeparatorStyleMenuItem: String, MenuItemProtocol {
    case none
    case singleLine
    
    var name: String {
        return rawValue.autoGeneratedMenuItemName
    }
    
	var viewController: UIViewController? {
        switch self {
        case .none:
            return TableViewSeparatorStyleNoneViewController()
        case .singleLine:
            return TableViewSeparatorStyleLineViewController()
        }
    }
}
