//
//  TableViewMenuItem.swift
//  UIKit-Swift
//
//  Created by Kamil Gomółka on 13/04/2022.
//

import UIKit

enum CellStyleMenuItem: String, MenuItemProtocol {
    case defaultFont
    case body
    case title3
    case longText
    
    var name: String {
        return rawValue.autoGeneratedMenuItemName
    }
    
    var viewController: UIViewController? {
        switch self {
        case .defaultFont:
            return CellStyleDefaultFontViewController()
        case .body:
            return CellStyleBodyViewController()
        case .title3:
            return CellStyleTitle3ViewController()
        case .longText:
            return CellStyleLongTextViewController()
        }
    }
}
